ONBOARDING: User Interface completed
priettt/kotlin-calculator pull request #1
Opened 2018-12-06 14:39 UTC by priettt

Finished activity_main.xml with the design of the calculator

Signed-off-by: Francisco Prieto francisco.prieto@globant.com

2018-12-06 14:43 UTC, priettt commented
![33f17e39-eb84-4573-bb70-5606479076fb](https://user-images.githubusercontent.com/26326883/49591015-0a462500-f94c-11e8-8244-12a3fac9d9f8.jpeg)

Here's the screenshot of the calculator!

2018-12-06 14:45 UTC, fanky10 approved these changes
Please pay more attention to avoiding hardcoded values in xml. It looks good though

2018-12-07 12:42 UTC, SartiMau requested changes

2018-12-07 12:42 UTC, SartiMau commented on app/src/main/res/layout/activity_main.xml
> +        android:elevation="4dp"
Use dimens please

2018-12-07 12:42 UTC, SartiMau commented on app/src/main/res/layout/activity_main.xml
>      <TextView
Use Styles for the styles attributes

2018-12-07 12:42 UTC, SartiMau commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_marginStart="1dp"
Use dimens please

2018-12-07 17:42 UTC, priettt commented on app/src/main/res/layout/activity_main.xml
> +        android:elevation="4dp"
done!

2018-12-07 17:42 UTC, priettt commented on app/src/main/res/layout/activity_main.xml
>      <TextView
done!

2018-12-07 17:42 UTC, priettt commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_marginStart="1dp"
done!

2018-12-07 17:54 UTC, SartiMau approved these changes

2018-12-07 17:56 UTC, fanky10 approved these changes
LG2M

2018-12-07 17:59 UTC, merged